import { OrderDto } from "./type";
const products = [
    {
      id: 673,
      name: "Juego de Utensilios de Cocina",
      description: "Juego completo de utensilios para todas tus necesidades de cocina.",
      price: 199.99,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDPEbAQlt_K2zql1JC4EaSJzHR6Nc8y_-PyQ&s",
    },
    {
      id: 674,
      name: "Teléfono Inteligente",
      description: "Último modelo de teléfono inteligente con alto rendimiento.",
      price: 599.99,
      img: null,
    },
    {
      id: 675,
      name: "Cámara",
      description: "Cámara de alta calidad para entusiastas de la fotografía.",
      price: 499.99,
      img: null,
    },
    {
      id: 676,
      name: "Ordenador Portátil",
      description: "Ordenador portátil de alto rendimiento para trabajar y jugar.",
      price: 899.99,
      img: null,
    },
    {
      id: 677,
      name: "Rastreador de Actividad",
      description: "Monitorea tus actividades físicas y salud.",
      price: 149.99,
      img: null,
    },
    {
      id: 678,
      name: "Auriculares Bluetooth",
      description: "Auriculares inalámbricos con calidad de sonido superior.",
      price: 79.99,
      img: null,
    },
    {
      id: 679,
      name: "Silla Ergonométrica",
      description: "Silla ergonómica ideal para oficina.",
      price: 199.99,
      img: null,
    },
    {
      id: 680,
      name: "Zapatillas de Running",
      description: "Zapatillas cómodas para correr en el uso diario.",
      price: 89.99,
      img: null,
    },
    {
      id: 681,
      name: "Chaqueta de Invierno",
      description: "Chaqueta cálida para el invierno.",
      price: 129.99,
      img: null,
    },
    {
      id: 682,
      name: "Juego de Herramientas",
      description: "Juego completo de herramientas para bricolaje.",
      price: 149.99,
      img: null,
    },
    {
      id: 683,
      name: "Lámpara LED",
      description: "Lámpara LED de bajo consumo para la casa.",
      price: 29.99,
      img: null,
    },
    {
      id: 684,
      name: "Escapada de Fin de Semana",
      description: "Paquete de escapada para un fin de semana.",
      price: 299.99,
      img: null,
    },
    {
      id: 685,
      name: "Licuadora",
      description: "Licuadora de alta velocidad para batidos y sopas.",
      price: 129.99,
      img: null,
    },
    {
      id: 686,
      name: "Balón de Fútbol",
      description: "Balón duradero para jugar al aire libre.",
      price: 25.99,
      img: null,
    },
    {
      id: 687,
      name: "Reloj Inteligente",
      description: "Reloj inteligente con múltiples funciones.",
      price: 249.99,
      img: null,
    },
    {
      id: 688,
      name: "Juego de Juegos de Mesa",
      description: "Diversión garantizada con este juego de mesa.",
      price: 39.99,
      img: null,
    },
    {
      id: 689,
      name: "Kit de Jardinería",
      description: "Kit completo para comenzar con la jardinería.",
      price: 59.99,
      img: null,
    },
    {
      id: 690,
      name: "Osito de Peluche",
      description: "Osito de peluche suave y abrazable para niños.",
      price: 19.99,
      img: null,
    },
    {
      id: 691,
      name: "Cesta de Picnic",
      description: "Cesta elegante para tus picnics al aire libre.",
      price: 89.99,
      img: null,
    },
    {
      id: 692,
      name: "Tocadiscos Vintage",
      description: "Tocadiscos con un diseño vintage y excelente calidad de sonido.",
      price: 399.99,
      img: null,
    },
    {
      id: 693,
      name: "Cámara Instantánea",
      description: "Cámara que imprime fotos al instante.",
      price: 249.99,
      img: null,
    },
    {
      id: 694,
      name: "Ventilador de Torre",
      description: "Ventilador de torre con varias velocidades y modo oscilante.",
      price: 89.99,
      img: null,
    },
    {
      id: 695,
      name: "Espejo de Maquillaje",
      description: "Espejo con iluminación LED y aumento.",
      price: 49.99,
      img: null,
    },
    {
      id: 696,
      name: "Botella de Agua Reutilizable",
      description: "Botella de agua ecológica y reutilizable.",
      price: 19.99,
      img: null,
    },
    {
      id: 697,
      name: "Termómetro Digital",
      description: "Termómetro digital preciso para medir la temperatura.",
      price: 15.99,
      img: null,
    },
    {
      id: 698,
      name: "Cargador Inalámbrico",
      description: "Cargador inalámbrico compatible con la mayoría de los teléfonos inteligentes.",
      price: 29.99,
      img: null,
    },
    {
      id: 699,
      name: "Organizador de Escritorio",
      description: "Organizador de escritorio con compartimentos múltiples.",
      price: 24.99,
      img: null,
    },
    {
      id: 700,
      name: "Colchón Inflable",
      description: "Colchón inflable de alta calidad para camping o invitados.",
      price: 79.99,
      img: null,
    },
    {
      id: 701,
      name: "Ropa de Cama 3 Piezas",
      description: "Juego de ropa de cama de 3 piezas, incluye funda de almohada, sábana y cobija.",
      price: 89.99,
      img: null,
    },
    {
      id: 702,
      name: "Cafetera de Goteo",
      description: "Cafetera de goteo con temporizador y función de mantener caliente.",
      price: 59.99,
      img: null,
    },
    {
      id: 703,
      name: "Pantalones Deportivos",
      description: "Pantalones deportivos cómodos y transpirables para entrenar.",
      price: 49.99,
      img: null,
    },
    {
      id: 704,
      name: "Plancha de Vapor",
      description: "Plancha de vapor con ajuste de temperatura y función de autolimpieza.",
      price: 49.99,
      img: null,
    },
    {
      id: 705,
      name: "Juguete Educativo",
      description: "Juguete educativo para el desarrollo cognitivo de los niños.",
      price: 34.99,
      img: null,
    },
    {
      id: 706,
      name: "Mochila de Senderismo",
      description: "Mochila resistente al agua ideal para senderismo y excursiones.",
      price: 99.99,
      img: null,
    },
    {
      id: 707,
      name: "Cinta Métrica",
      description: "Cinta métrica de 5 metros para uso en la construcción y medidas.",
      price: 15.99,
      img: null,
    },
    {
      id: 708,
      name: "Caja de Herramientas",
      description: "Caja de herramientas resistente con múltiples compartimentos.",
      price: 89.99,
      img: null,
    },
    {
      id: 709,
      name: "Altavoz Bluetooth",
      description: "Altavoz Bluetooth portátil con sonido de alta calidad.",
      price: 69.99,
      img: null,
    },
    {
      id: 710,
      name: "Escoba y Recogedor",
      description: "Juego de escoba y recogedor para limpieza doméstica.",
      price: 19.99,
      img: null,
    },
    {
      id: 711,
      name: "Tenedor de Cocina",
      description: "Tenedor de cocina de acero inoxidable con mango ergonómico.",
      price: 14.99,
      img: null,
    },
    {
      id: 712,
      name: "Gafas de Sol",
      description: "Gafas de sol con protección UV y diseño moderno.",
      price: 39.99,
      img: null,
    },
    {
      id: 713,
      name: "Soporte para Laptop",
      description: "Soporte ajustable para laptop que mejora la ergonomía.",
      price: 34.99,
      img: null,
    },
    {
      id: 714,
      name: "Ropa de Cama para Niños",
      description: "Juego de ropa de cama con diseños infantiles.",
      price: 69.99,
      img: null,
    },
    {
      id: 715,
      name: "Bolsa de Deporte",
      description: "Bolsa de deporte con múltiples compartimentos para tus accesorios.",
      price: 49.99,
      img: null,
    },
    {
      id: 716,
      name: "Lámpara de Escritorio",
      description: "Lámpara de escritorio con ajuste de intensidad de luz.",
      price: 39.99,
      img: null,
    },
    {
      id: 717,
      name: "Almohada de Espuma",
      description: "Almohada ergonómica de espuma con memoria para un sueño cómodo.",
      price: 59.99,
      img: null,
    },
    {
      id: 718,
      name: "Dispenser de Agua",
      description: "Dispenser de agua con capacidad para 5 litros.",
      price: 79.99,
      img: null,
    },
    {
      id: 719,
      name: "Batidora de Mano",
      description: "Batidora de mano con múltiples velocidades y accesorios.",
      price: 39.99,
      img: null,
    },
    {
      id: 720,
      name: "Saco de Dormir",
      description: "Saco de dormir con aislamiento térmico para acampadas.",
      price: 89.99,
      img: null,
    },
    {
      id: 721,
      name: "Portafolios de Cuero",
      description: "Portafolios de cuero con compartimentos para documentos y dispositivos.",
      price: 129.99,
      img: null,
    },
    {
      id: 722,
      name: "Jardín Vertical",
      description: "Sistema de jardín vertical para cultivo en espacios reducidos.",
      price: 139.99,
      img: null,
    },
    {
      id: 723,
      name: "Juegos de Construcción",
      description: "Juego de bloques de construcción para desarrollar habilidades motoras.",
      price: 39.99,
      img: null,
    },
    {
      id: 724,
      name: "Cámara de Seguridad",
      description: "Cámara de seguridad con visión nocturna y conexión Wi-Fi.",
      price: 149.99,
      img: null,
    },
    {
      id: 725,
      name: "Estación Meteorológica",
      description: "Estación meteorológica para monitorear el clima en casa.",
      price: 79.99,
      img: null,
    },
    {
      id: 726,
      name: "Botellas Reutilizables",
      description: "Botellas reutilizables para agua con tapa hermética.",
      price: 19.99,
      img: null,
    },
    {
      id: 727,
      name: "Ropa Interior",
      description: "Ropa interior cómoda y transpirable para todos los días.",
      price: 29.99,
      img: null,
    },
    {
      id: 728,
      name: "Set de Maquillaje",
      description: "Set completo de maquillaje con varios productos y herramientas.",
      price: 69.99,
      img: null,
    },
    {
      id: 729,
      name: "Aspiradora Robot",
      description: "Aspiradora robot con función de mapeo y programación.",
      price: 249.99,
      img: null,
    },
    {
      id: 730,
      name: "Maleta de Viaje",
      description: "Maleta de viaje con ruedas y compartimentos organizadores.",
      price: 119.99,
      img: null,
    },
    {
      id: 731,
      name: "Grill de Contacto",
      description: "Grill de contacto con placas antiadherentes y ajuste de temperatura.",
      price: 89.99,
      img: null,
    },
    {
      id: 732,
      name: "Cuna para Bebé",
      description: "Cuna para bebé con barandillas ajustables y colchón incluido.",
      price: 199.99,
      img: null,
    },
    {
      id: 733,
      name: "Guantes de Cocina",
      description: "Guantes de cocina resistentes al calor y con diseño antideslizante.",
      price: 18.99,
      img: null,
    },
    {
      id: 734,
      name: "Soporte para Celular",
      description: "Soporte ajustable para celular con base antideslizante.",
      price: 24.99,
      img: null,
    },
    {
      id: 735,
      name: "Lámpara de Lava",
      description: "Lámpara de lava decorativa con efectos de movimiento hipnóticos.",
      price: 29.99,
      img: null,
    },
    {
      id: 736,
      name: "Espejo con Luz LED",
      description: "Espejo con iluminación LED ajustable para un maquillaje preciso.",
      price: 39.99,
      img: null,
    },
    {
      id: 737,
      name: "Baterías Recargables",
      description: "Paquete de baterías recargables para dispositivos electrónicos.",
      price: 22.99,
      img: null,
    },
    {
      id: 738,
      name: "Tetera Eléctrica",
      description: "Tetera eléctrica con función de apagado automático y ajuste de temperatura.",
      price: 49.99,
      img: null,
    },
    {
      id: 739,
      name: "Secador de Pelo",
      description: "Secador de pelo con múltiples velocidades y ajuste de temperatura.",
      price: 59.99,
      img: null,
    },
    {
      id: 740,
      name: "Tijeras de Cocina",
      description: "Tijeras de cocina multiusos con mango ergonómico.",
      price: 14.99,
      img: null,
    },
    {
      id: 741,
      name: "Pulsera de Actividad",
      description: "Pulsera de actividad con monitor de frecuencia cardíaca y seguimiento de sueño.",
      price: 89.99,
      img: null,
    },
    {
      id: 742,
      name: "Cuaderno de Notas",
      description: "Cuaderno de notas con papel de alta calidad y encuadernación dura.",
      price: 14.99,
      img: null,
    },
    {
      id: 743,
      name: "Porta Documentos",
      description: "Porta documentos elegante y resistente con múltiples compartimentos.",
      price: 39.99,
      img: null,
    },
    {
      id: 744,
      name: "Caja Fuerte",
      description: "Caja fuerte de seguridad con combinación digital y compartimentos internos.",
      price: 159.99,
      img: null,
    },
    {
      id: 745,
      name: "Zapatillas de Casa",
      description: "Zapatillas de casa cómodas y cálidas para el hogar.",
      price: 29.99,
      img: null,
    },
    {
      id: 746,
      name: "Sistema de Sonido",
      description: "Sistema de sonido con altavoces de alta calidad y conectividad Bluetooth.",
      price: 199.99,
      img: null,
    },
    {
      id: 747,
      name: "Maletín para Laptop",
      description: "Maletín para laptop con compartimentos acolchados y diseño profesional.",
      price: 89.99,
      img: null,
    },
    {
      id: 748,
      name: "Lámpara de Pie",
      description: "Lámpara de pie con diseño elegante y ajuste de altura.",
      price: 119.99,
      img: null,
    },
    {
      id: 749,
      name: "Hidrolavadora",
      description: "Hidrolavadora de alta presión ideal para limpieza exterior.",
      price: 229.99,
      img: null,
    },
    {
      id: 750,
      name: "Kit de Maquillaje Profesional",
      description: "Kit de maquillaje con una variedad de colores y productos profesionales.",
      price: 89.99,
      img: null,
    },
    {
      id: 751,
      name: "Estufa de Gas",
      description: "Estufa de gas con múltiples quemadores y función de encendido automático.",
      price: 199.99,
      img: null,
    },
    {
      id: 752,
      name: "Set de Herramientas",
      description: "Set completo de herramientas para reparaciones y proyectos caseros.",
      price: 99.99,
      img: null,
    },
    {
      id: 753,
      name: "Sombrilla para Patio",
      description: "Sombrilla para patio con base pesada y ajuste de inclinación.",
      price: 129.99,
      img: null,
    },
    {
      id: 754,
      name: "Juego de Ollas",
      description: "Juego de ollas de acero inoxidable con tapas a juego.",
      price: 119.99,
      img: null,
    },
    {
      id: 755,
      name: "Funda para Sofá",
      description: "Funda para sofá a prueba de manchas y fácil de instalar.",
      price: 69.99,
      img: null,
    },
    {
      id: 756,
      name: "Gimnasio de Casa",
      description: "Equipo de gimnasio de casa con pesas, bandas y esterilla.",
      price: 299.99,
      img: null,
    },
    {
      id: 757,
      name: "Aparato de Ejercicio",
      description: "Aparato de ejercicio multifuncional para entrenamiento en casa.",
      price: 249.99,
      img: null,
    },
    {
      id: 758,
      name: "Parrilla Eléctrica",
      description: "Parrilla eléctrica con temperatura regulable y superficie antiadherente.",
      price: 79.99,
      img: null,
    },
    {
      id: 759,
      name: "Mini Refrigerador",
      description: "Mini refrigerador compacto ideal para oficinas o dormitorios.",
      price: 149.99,
      img: null,
    },
    {
      id: 760,
      name: "Ropa de Baño",
      description: "Ropa de baño de alta calidad para hombres y mujeres.",
      price: 39.99,
      img: null,
    },
    {
      id: 761,
      name: "Cesta de Ropa",
      description: "Cesta de ropa con diseño moderno y material resistente.",
      price: 24.99,
      img: null,
    },
    {
      id: 762,
      name: "Kit de Pintura",
      description: "Kit completo para pintura con pinceles, rodillos y pinturas.",
      price: 54.99,
      img: null,
    },
    {
      id: 763,
      name: "Batería Externa",
      description: "Batería externa de alta capacidad para cargar dispositivos móviles.",
      price: 39.99,
      img: null,
    },
    {
      id: 764,
      name: "Set de Jardinería",
      description: "Set completo de jardinería con herramientas esenciales y guantes.",
      price: 44.99,
      img: null,
    },
    {
      id: 765,
      name: "Set de Cubiertos",
      description: "Set de cubiertos de acero inoxidable con diseño elegante.",
      price: 39.99,
      img: null,
    },
    {
      id: 766,
      name: "Caja de Almacenamiento",
      description: "Caja de almacenamiento con tapa y capacidad para objetos pequeños.",
      price: 29.99,
      img: null,
    },
    {
      id: 767,
      name: "Gafas de Lectura",
      description: "Gafas de lectura con lentes antirreflejantes y diseño moderno.",
      price: 19.99,
      img: null,
    },
    {
      id: 768,
      name: "test 32",
      description: "This is a new product description.",
      price: 19.99,
      img: "https://example.com/product_image.jpg",
    },
  ]

const getRandomInt = (min: number, max: number): number => Math.floor(Math.random() * (max - min + 1)) + min;

// Generate sample orders
const generateSampleOrders = (numOrders: number): OrderDto[] => {
  const orders: OrderDto[] = [];

  for (let i = 0; i < numOrders; i++) {
    const numProducts = getRandomInt(1, 5); // Random number of products
    const items = [];

    let totalAmount = 0;

    for (let j = 0; j < numProducts; j++) {
      const product = products[getRandomInt(0, products.length - 1)]; // Select random product
      const quantity = getRandomInt(1, 10); // Random quantity

      const pricePay = product.price * quantity;
      const discount = 1; // Adjust discount logic if needed

      items.push({
        productId: product.id,
        quantity,
        pricePay,
        discount,
      });

      totalAmount += pricePay;
    }

    orders.push({
      id: null,
      idUser: getRandomInt(1, 50), // Random user ID
      totalAmount,
      startDate: null, // Set startDate as needed
      endDate: null, // Set endDate as needed
      state: "", // Set state as needed
      items,
    });
  }

  return orders;
};

// Example usage
export const sampleOrders = generateSampleOrders(250);