// sampleCategories.ts

export const sampleCategories = [
    'Electrónica',
    'Moda',
    'Hogar',
    'Deportes',
    'Juguetes',
    'Libros',
    'Alimentos',
    'Belleza',
    'Mascotas',
    'Automóviles',
    'Electrodomésticos',
    'Ropa y Accesorios',
    'Salud y Cuidado Personal',
    'Oficina y Papelería',
    'Herramientas y Construcción',
    'Jardinería',
    'Bebés y Niños',
    'Videojuegos',
    'Instrumentos Musicales',
    'Viajes y Equipaje',
    'Joyería y Relojes',
    'Arte y Artesanía',
    'Cocina y Comedor',
    'Deportes de Aventura',
    'Tecnología',
    'Cine y Fotografía',
    'Cuidado del Cabello',
    'Productos Ecológicos',
    'Gourmet y Delicatessen',
    'Relojes Inteligentes',
    'Accesorios para Vehículos',
    'Mobiliario de Exterior',
    'Fitness y Gimnasio',
    'Nutrición Deportiva',
    'Accesorios para Mascotas',
    'Suministros Médicos',
    'Suministros de Limpieza',
    'Accesorios para Viaje',
    'Seguridad y Vigilancia',
    'Accesorios para Móviles',
    'Juegos de Mesa',
    'Productos para el Cuidado de la Piel',
    'Decoración del Hogar',
    'Accesorios para Cámaras',
    'Ropa de Dormir',
    'Caza y Pesca',
    'Camping y Aire Libre',
    'Bicicletas y Accesorios',
    'Relojería',
    'Productos para el Baño',
    'Textiles del Hogar',
    'Productos de Papelería',
    'Accesorios de Cocina'
];
