import { User } from "./types";

const  ListaUSers = [
    {"name": "Alice Johnson", "email": "alice.johnson@example.com", "city": "New York", "password": "password123", "role": "USER"},
    {"name": "Bob Smith", "email": "bob.smith@example.com", "city": "Los Angeles", "password": "password123", "role": "USER"},
    {"name": "Charlie Brown", "email": "charlie.brown@example.com", "city": "Chicago", "password": "password123", "role": "USER"},
    {"name": "David Wilson", "email": "david.wilson@example.com", "city": "Houston", "password": "password123", "role": "USER"},
    {"name": "Eva Davis", "email": "eva.davis@example.com", "city": "Phoenix", "password": "password123", "role": "USER"},
    {"name": "Frank Miller", "email": "frank.miller@example.com", "city": "Philadelphia", "password": "password123", "role": "USER"},
    {"name": "Grace Lee", "email": "grace.lee@example.com", "city": "San Antonio", "password": "password123", "role": "USER"},
    {"name": "Henry Taylor", "email": "henry.taylor@example.com", "city": "San Diego", "password": "password123", "role": "USER"},
    {"name": "Ivy Anderson", "email": "ivy.anderson@example.com", "city": "Dallas", "password": "password123", "role": "USER"},
    {"name": "James Martinez", "email": "james.martinez@example.com", "city": "San Jose", "password": "password123", "role": "USER"},
    {"name": "Katherine Thompson", "email": "katherine.thompson@example.com", "city": "Austin", "password": "password123", "role": "USER"},
    {"name": "Liam White", "email": "liam.white@example.com", "city": "Jacksonville", "password": "password123", "role": "USER"},
    {"name": "Mia Harris", "email": "mia.harris@example.com", "city": "San Francisco", "password": "password123", "role": "USER"},
    {"name": "Noah Clark", "email": "noah.clark@example.com", "city": "Columbus", "password": "password123", "role": "USER"},
    {"name": "Olivia Lewis", "email": "olivia.lewis@example.com", "city": "Indianapolis", "password": "password123", "role": "USER"},
    {"name": "Paul Walker", "email": "paul.walker@example.com", "city": "Fort Worth", "password": "password123", "role": "USER"},
    {"name": "Quinn Robinson", "email": "quinn.robinson@example.com", "city": "Charlotte", "password": "password123", "role": "USER"},
    {"name": "Rachel Young", "email": "rachel.young@example.com", "city": "Detroit", "password": "password123", "role": "USER"},
    {"name": "Steve Adams", "email": "steve.adams@example.com", "city": "El Paso", "password": "password123", "role": "USER"},
    {"name": "Tina King", "email": "tina.king@example.com", "city": "Memphis", "password": "password123", "role": "USER"},
    {"name": "Ursula Scott", "email": "ursula.scott@example.com", "city": "Boston", "password": "password123", "role": "USER"},
    {"name": "Victor Green", "email": "victor.green@example.com", "city": "Seattle", "password": "password123", "role": "USER"},
    {"name": "Wendy Hall", "email": "wendy.hall@example.com", "city": "Denver", "password": "password123", "role": "USER"},
    {"name": "Xander Allen", "email": "xander.allen@example.com", "city": "Washington", "password": "password123", "role": "USER"},
    {"name": "Yara Wright", "email": "yara.wright@example.com", "city": "Nashville", "password": "password123", "role": "USER"},
    {"name": "Zachary Young", "email": "zachary.young@example.com", "city": "Baltimore", "password": "password123", "role": "USER"},
    {"name": "Ava Martinez", "email": "ava.martinez@example.com", "city": "Omaha", "password": "password123", "role": "USER"},
    {"name": "Ben Johnson", "email": "ben.johnson@example.com", "city": "Las Vegas", "password": "password123", "role": "USER"},
    {"name": "Caitlin Lee", "email": "caitlin.lee@example.com", "city": "Louisville", "password": "password123", "role": "USER"},
    {"name": "Daniel Moore", "email": "daniel.moore@example.com", "city": "Milwaukee", "password": "password123", "role": "USER"},
    {"name": "Emma Lewis", "email": "emma.lewis@example.com", "city": "Albuquerque", "password": "password123", "role": "USER"},
    {"name": "Felix Davis", "email": "felix.davis@example.com", "city": "Tucson", "password": "password123", "role": "USER"},
    {"name": "Gina Hernandez", "email": "gina.hernandez@example.com", "city": "Fresno", "password": "password123", "role": "USER"},
    {"name": "Henry Taylor", "email": "henry.taylor@example.com", "city": "Sacramento", "password": "password123", "role": "USER"},
    {"name": "Isabel Moore", "email": "isabel.moore@example.com", "city": "Kansas City", "password": "password123", "role": "USER"},
    {"name": "Jack Wilson", "email": "jack.wilson@example.com", "city": "Mesa", "password": "password123", "role": "USER"},
    {"name": "Kylie White", "email": "kylie.white@example.com", "city": "Virginia Beach", "password": "password123", "role": "USER"},
    {"name": "Liam Thomas", "email": "liam.thomas@example.com", "city": "Atlanta", "password": "password123", "role": "USER"},
    {"name": "Mia Walker", "email": "mia.walker@example.com", "city": "Colorado Springs", "password": "password123", "role": "USER"},
    {"name": "Noah Scott", "email": "noah.scott@example.com", "city": "Omaha", "password": "password123", "role": "USER"},
    {"name": "Olivia Robinson", "email": "olivia.robinson@example.com", "city": "Raleigh", "password": "password123", "role": "USER"},
    {"name": "Patrick Harris", "email": "patrick.harris@example.com", "city": "Miami", "password": "password123", "role": "USER"},
    {"name": "Quinn Evans", "email": "quinn.evans@example.com", "city": "Cleveland", "password": "password123", "role": "USER"},
    {"name": "Rachel Martin", "email": "rachel.martin@example.com", "city": "Tulsa", "password": "password123", "role": "USER"},
    {"name": "Sam Gonzalez", "email": "sam.gonzalez@example.com", "city": "Oakland", "password": "password123", "role": "USER"},
    {"name": "Tina Robinson", "email": "tina.robinson@example.com", "city": "Minneapolis", "password": "password123", "role": "USER"},
    {"name": "Ulysses Ramirez", "email": "ulysses.ramirez@example.com", "city": "Wichita", "password": "password123", "role": "USER"},
    {"name": "Vera Perez", "email": "vera.perez@example.com", "city": "Arlington", "password": "password123", "role": "USER"},
    {"name": "Walter Sanders", "email": "walter.sanders@example.com", "city": "Bakersfield", "password": "password123", "role": "USER"},
    {"name": "Xena Brooks", "email": "xena.brooks@example.com", "city": "Tampa", "password": "password123", "role": "USER"},
    {"name": "Yvonne Murphy", "email": "yvonne.murphy@example.com", "city": "Honolulu", "password": "password123", "role": "USER"},
    {"name": "Zane Bennett", "email": "zane.bennett@example.com", "city": "Aurora", "password": "password123", "role": "USER"}
]

export const sampleUsers = ListaUSers;

